### ISSUE TITLE
Changing Words in a file

### ISSUE THREAD

**Issue by KiritoAUT** [learnbyexample/TUI-apps#5]
In Q:43 you replace the words "tea&coffe" with "cake&toffee" which change in the purchases.txt file aswell. In the following questions with purchasese.txt the expected output still is with the words "coffee&tea". So no matter what you do, you get it wrong.

![Bild_2023-10-31_083509547](https://github.com/learnbyexample/TUI-apps/assets/123743564/b5b1b36a-a374-456e-b91c-3b677e82ce2d)

![image](https://github.com/learnbyexample/TUI-apps/assets/123743564/3d8e47d3-df2c-419d-ba8b-331331364d5f)

**Comment by learnbyexample** [comment]
By default, `sed` will not change the input file itself. You'll need to use the `-i` option to write back the changes.

In the screenshot you've shown, `-i` option is *NOT* used, so I'm not sure how the input file got changed for you.

**Comment by KiritoAUT** [comment]
Its not a bug, must have been something with my client. Please close the issue, I fixed it with -i and placed it back as it was. Thank you for your answer. Happy Halloween
